services:

    trinity.logger.elastic.log.service:
      class: Trinity\Bundle\LoggerBundle\Services\ElasticLogService
      arguments:
        - "%trinity.logger.elastic_host%"
        - "%trinity.logger.elastic_managed_index%"

    trinity.logger.elastic.read.log.service:
      class: Trinity\Bundle\LoggerBundle\Services\ElasticReadLogService
      arguments:
        - "%trinity.logger.elastic_host%"
        - '@doctrine.orm.default_entity_manager'
        - "%trinity.logger.elastic_managed_index%"
        - "%trinity.logger.base.entities.path%"