services:

    trinity.dynamo.log.service:
      class: Trinity\Bundle\LoggerBundle\Services\DynamoDBService
      arguments:
        - "%trinity.logger.dynamo_host%"
        - "%trinity.logger.dynamo_port%"
        - "%trinity.logger.aws_key%"
        - "%trinity.logger.aws_secret%"
        - "%trinity.logger.aws_region%"

    trinity.elastic.log.service:
      class: Trinity\Bundle\LoggerBundle\Services\ElasticLogService
      arguments: